[uss_qualifier] add scd scenario checking that CR deletion requires the correct OVN
interuss/monitoring pull request #762
Opened 2024-08-28 19:37 UTC by Shastick

The constraint reference (CR) equivalent of #761: ensure that a DSS will properly compare the passed OVN to the one in store before deleting a CR.

Similarly to the other PR, this PR will fail as long as we have not released a new DSS image, if we decide to ship the update to the configuration within this PR.

This is the second step towards fixing #759

2024-09-05 19:51 UTC, Shastick commented
Taking to draft: requires a last fix/adaptation for the `utm_implementation_us` configuration

2024-09-10 12:14 UTC, mickmis approved these changes
LGTM

2024-09-10 12:14 UTC, mickmis commented on monitoring/uss_qualifier/scenarios/astm/utm/dss/constraint_ref_simple.py
> +    CR_TYPE = register_resource_type(397, "Constraint Reference")
Update of the comment mentioning the next index?

2024-09-11 12:01 UTC, mickmis requested changes
I think two files got introduced in the PR but sohuldn't?

2024-09-11 17:16 UTC, Shastick commented
> I think two files got introduced in the PR but sohuldn't?

Indeed. They have been removed.

2024-09-12 07:03 UTC, mickmis approved these changes

2024-09-12 07:03 UTC, merged