[uss_qualifier] netrid: cover net0260 timestamp accuracy
interuss/monitoring pull request #822
Opened 2024-10-28 11:59 UTC by Shastick

Expand the generic `NominalBehavior` scenario to check:
 - for the presence of the required `timestamp_accuracy` field
 - that the field contains the injected value

Because of the way implicit dicts works, checking for the presence of this field requires to look at the raw response Json (see comment in the code)

Part of #754

2024-10-29 13:34 UTC, mickmis commented on monitoring/uss_qualifier/scenarios/astm/netrid/v22a/nominal_behavior.md
> +**[astm.f3411.v22a.NET0260,Table1,5](../../../../requirements/astm/f3411/v22a.md)** requires that relevant Remote ID data, consistent with the common data dictionary, be reported by the Service Provi
Could you be more specific as to what would fail that check?

In addition I see that the implementation does a strict equality check, I don't think that's reasonable. 
First because it is a float value so at least it should be an interval check. 
Then, I don't think it would necessary be a failing criteria for a SP to report an accuracy different than what is injected. E.g. if this accuracy is implemented as buckets by the SP. 
The way I interpret it, given that the accuracy is meant to reflect an uncertainty bound, reporting more uncertainty than the reality is not wrong, however reporting less uncertainty than reality is wrong.

2024-10-29 16:03 UTC, Shastick commented on monitoring/uss_qualifier/scenarios/astm/netrid/v22a/nominal_behavior.md
> +**[astm.f3411.v22a.NET0260,Table1,5](../../../../requirements/astm/f3411/v22a.md)** requires that relevant Remote ID data, consistent with the common data dictionary, be reported by the Service Provi
Regarding the wording: I've been reusing wording for similar checks in the same file to remain consistent. I can make the end of the sentence more compact, but if we are not happy with the overall wording I'd change the whole file in a separate PR

2024-10-29 16:07 UTC, Shastick commented on monitoring/uss_qualifier/scenarios/astm/netrid/v22a/nominal_behavior.md
> +**[astm.f3411.v22a.NET0260,Table1,5](../../../../requirements/astm/f3411/v22a.md)** requires that relevant Remote ID data, consistent with the common data dictionary, be reported by the Service Provi
Regarding the exact check for the accuracy: indeed, we should probably allow a little buffer for float comparison. However the spec is quite precise as to what precision.

About checking for bounds, I disagree: the spec states

>  [...] Expressed in seconds, precise to 1/10ths of seconds. The accuracy reflects the 95% uncertainty bound value for the timestamp.

Changing the bound would mean that the value does not reflect the 95% uncertainty bound anymore: here I see no reason why an SP should be allowed to change the value by a tenth of a second or more.

2024-11-14 14:19 UTC, mickmis requested changes
LGTM except for the wrong requirement, rest are nits.

2024-11-14 14:19 UTC, mickmis commented on monitoring/uss_qualifier/scenarios/astm/netrid/v22a/nominal_behavior.md
> +**[astm.f3411.v22a.NET0260,Table1,5](../../../../requirements/astm/f3411/v22a.md)** requires that relevant Remote ID data, consistent with the common data dictionary, be reported by the Service Provi
Wrong requirement:
```suggestion
**[astm.f3411.v22a.NET0260,Table1,6](../../../../requirements/astm/f3411/v22a.md)** requires that relevant Remote ID data, consistent with the common data dictionary, be reported by the Service Provider.  The observed timestamp accuracy differs from the injected one.
```

2024-11-14 14:19 UTC, mickmis commented on monitoring/uss_qualifier/scenarios/astm/netrid/display_data_evaluator.py
> +            if "timestamp_accuracy" in raw_state:
nit: put in else of above?

2024-11-14 14:19 UTC, mickmis commented on monitoring/uss_qualifier/scenarios/astm/netrid/display_data_evaluator.py
> +TIMESTAMP_ACCURACY_EPSILON = 0.05
nit: Suffix with `_PRECISION` for consistency?

2024-11-14 14:42 UTC, mickmis approved these changes

2024-11-14 14:45 UTC, merged